# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-19 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_auto_20170819_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='my_file',
            field=models.FileField(upload_to='/media', verbose_name='文件'),
        ),
    ]
