# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-19 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0012_auto_20170819_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='描述'),
        ),
    ]
